name: Update GitHub Package

on:
  push:
    branches:
      - main

jobs:
  update-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create new file
        run: echo "This is a new file content" > newfile.txt

      - name: Add new file to package
        run: |
          echo "{}" | jq --arg file newfile.txt '.files += [$file]' > updated-package.json
          curl -u ${{ secrets.GITHUB_TOKEN }} -X PUT -H "Content-Type: application/json" \
            -d @updated-package.json \
            "https://api.github.com/repos/<OWNER>/<REPO>/packages/<PACKAGE_NAME>/versions/<PACKAGE_VERSION>"
