name: Manage GitHub Package Snapshots

on:
  push:
    branches:
      - main

jobs:
  manage-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh jq

      - name: Authenticate with GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: List package versions
        id: list_versions
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /orgs/:org/packages/container/:package/versions \
            | jq -r '.[] | select(.metadata.container.tags[] | contains("snapshot")) | select(.metadata.container.groupId == "restart.admin") | .id' > versions.txt

