name: Action One

on:
  workflow_run:
    workflows: ["Actions Orchestrator"]
    types:
      - completed

jobs:
  dummy_job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment from Action One
        run: echo "Running Action One in ${{ inputs.environment }}"
