name: Actions Orchestrator

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the actions (dev, dev2, prod)'
        required: true
        default: 'dev'

jobs:
  start_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Trigger Action One
        id: action_one
        uses: ./.github/workflows/action_one.yaml
        with:
          environment: ${{ env.ENVIRONMENT }}

  trigger_action_two:
    runs-on: ubuntu-latest
    needs: start_orchestrator
    if: ${{ success() }}
    steps:
      - name: Trigger Action Two
        id: action_two
        uses: ./.github/workflows/action_two.yaml
        with:
          environment: ${{ env.ENVIRONMENT }}

  trigger_action_three:
    runs-on: ubuntu-latest
    needs: trigger_action_two
    if: ${{ success() }}
    steps:
      - name: Trigger Action Three
        id: action_three
        uses: ./.github/workflows/action_three.yaml
        with:
          environment: ${{ env.ENVIRONMENT }}
