name: Action Two

on:
  workflow_dispatch:

jobs:
  dummy_job_two:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment from Action Two
        run: echo "Running Action Two in ${{ inputs.environment }}"
