name: Manually Upload File

on:
  workflow_dispatch:  # Triggered manually

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create test.txt
        run: echo "Hello, world!" > test.txt

      - name: Upload to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
           -H "Authorization: token $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
           --data-binary @test.txt \
           "https://maven.pkg.github.com/<USERNAME>/<REPOSITORY>/com/example/test.txt"
