name: Deploy to Prod

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: 'string'

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print Environment From Deploy to Prod
        run: echo "Running Deploy to Prod in:${{ inputs.environment }}"