name: Download test file

on:
  workflow_dispatch:

jobs:
  download-and-use-logs:
    runs-on: ubuntu-latest
    steps:
      - name: List files before download
        run: ls -al

      - name: Print working directory
        run: pwd

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file
          path: ./new_path

      - name: List files after download
        run: ls -al new_path

      - name: Read and use test.txt
        run: |
          content=$(cat new_path/test.txt)
          echo "Read content: $content"
