name: Download test file

on:
  workflow_dispatch:
    workflow_run:
      workflows: [ "Upload test file" ]
      types:
        - completed

jobs:
  download-and-use-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -al new_path

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read and use test.txt
        run: |
          content=$(cat new_path/test.txt)
          echo "Read content: $content"
