name: Dummy

on:
  workflow_dispatch:

jobs:
  start_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print project structure
        run: |
          ls -R .github/workflows 
          # Optionally, you can print specific directories or files
          # Example:
          # ls -R .github/workflows  

      - name: Trigger Action One
        uses: ./.github/workflows/action.yml

