name: Dummy

on:
  workflow_dispatch:

jobs:
  start_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Action One
        uses: NewAntik/Restart-Back--Admin--Front/.github/workflows/action.yaml

