name: Restart backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
  workflow_run:
    workflows: ["Deploy artifacts"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and Upload Environment File
        if: ${{ github.event.inputs.environment != 'dev' }}
        id: create-file
        run: |
          echo "Creating file for environment: ${{ github.event.inputs.environment }}"
          echo "${{ github.event.inputs.environment }}" > ${{ github.event.inputs.environment }}-backend.txt

          echo "::set-output name=filename::${{ github.event.inputs.environment }}-backend.txt"
          echo "Uploading ${{ github.event.inputs.environment }}-backend.txt to GitHub Packages..."
          echo "${{ github.event.inputs.environment }}-backend.txt" > $GITHUB_WORKSPACE/file.txt
          echo "::set-output name=file::$GITHUB_WORKSPACE/file.txt"
          echo "Done uploading."

      - name: Download Environment File
        if: ${{ github.event.inputs.environment != 'dev' }}
        id: download-file
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.create-file.outputs.filename }}
          path: $GITHUB_WORKSPACE
