name: Restart frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
  workflow_run:
    workflows: ["Restart admin"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ vars.INSTANCE_HOSTNAME }}
          username: ${{ vars.INSTANCE_USERNAME }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: |
            docker ps -a --filter label=${{ vars.FRONTEND_DEPLOYMENT_NAME }}
            if [ -n "$(docker ps -a --filter label=${{ vars.FRONTEND_DEPLOYMENT_NAME }} -q)" ]; then 
               docker stop ${{ vars.FRONTEND_DEPLOYMENT_NAME }}
               docker rm ${{ vars.FRONTEND_DEPLOYMENT_NAME }}
            fi;

            docker pull ${{ vars.FRONTEND_DOCKERHUB_REPOSITORY }}

            docker run -e VIRTUAL_HOST=${{ vars.FRONTEND_APP_HOSTNAME }} -e SPRING_CLOUD_CONFIG_URI=http://${{ vars.CONFIG_APP_HOSTNAME }} -e SPRING_CLOUD_CONFIG_FAIL-FAST=true -e SPRING_APPLICATION_NAME=${{ vars.FRONTEND_APP_NAME }} -e SPRING_PROFILES_ACTIVE=${{ vars.APP_PROFILE }} -e SPRING_CLOUD_CONFIG_USERNAME=${{ vars.CONFIG_USER }} -e SPRING_CLOUD_CONFIG_PASSWORD={noop}${{ vars.CONFIG_PASSWORD }} -e SPRING_CLOUD_CONFIG_DISCOVER_ENABLED=false -e EUREKA_CLIENT_ENABLED=false -v  ${{ vars.FRONTEND_SERVER_LOG_DIR }}:${{ vars.FRONTEND_LOG_DIR }} -d -p ${{ vars.FRONTEND_APP_PORT }}:80 --name ${{ vars.FRONTEND_DEPLOYMENT_NAME }} --network ${{ vars.DOCKER_NETWORK }} --label ${{ vars.FRONTEND_DEPLOYMENT_NAME }} ${{ vars.FRONTEND_DOCKERHUB_REPOSITORY }}