name: Upload File to GitHub Packages

on:
  workflow_dispatch:  # Triggered manually

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test.txt
        run: echo "Hello, world!" > test.txt

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build and publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES_URL: ${{ secrets.PACKAGES_URL }}
          NAME: ${{ secrets.NAME }}
          PAT: ${{ secrets.PAT }}
        run: |
          ./gradlew publish
