name: Publish File to GitHub Packages

on:
  workflow_dispatch:  # Triggered manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test.txt
        run: echo "Hello, world!" > test.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          echo "registry=https://npm.pkg.github.com/NewAntik/Restart-Back--Admin--Front" >> ~/.npmrc
          npm publish test.txt --access public
