name: Upload File to GitHub Packages

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Append GitHub Package Authentication to gradle.properties
        run: |
          echo "github_package_username=${{ secrets.NAME }}" >> ~/.gradle/gradle.properties
          echo "github_package_token=${{ secrets.PAT }}" >> ~/.gradle/gradle.properties
          echo "github_package_Url=${{ secrets.PACKAGES_URL }}" >> ~/.gradle/gradle.properties

      - name: Create test.txt
        run: echo "This is a test file. Commit SHA" ${{ github.sha }} > test.txt

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build and publish to GitHub Packages
        run: |
          ./gradlew publish
        env:
          PACKAGES_URL: ${{ secrets.PACKAGES_URL }}
          NAME: ${{ secrets.NAME }}
          PAT: ${{ secrets.PAT }}

