name: Publish File to GitHub Packages

on:
  push:
    branches:
      - main  # Adjust as per your branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test.txt
        run: echo "Hello, world!" > test.txt

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          echo "registry=https://npm.pkg.github.com/NewAntik/Restart-Back--Admin--Front" >> ~/.npmrc
          npm publish --access public
