name: Upload test file

on:
  workflow_dispatch:

jobs:
  get-and-upload-logs:
    runs-on: ubuntu-latest
    steps:

      - name: Create AntonFile.txt
        run: echo "Hello, world!" > AntonFile.txt

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: AntonFile
          path: AntonFile.txt
